#define Ceil(x) 																	(-round(-(x)))
#define Floor(x) 																	round(x)
#define ischaracter(m)																istype(m, /character)
#define isprojectile(p)																istype(p, /projectile)
#define islist(l)																	istype(l, /list)
#define isskill(s)																	istype(s, /skill)